// <auto-generated />
using System;
using MediCita.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCita.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(MediCitaDbContext))]
    [Migration("20260817022205_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SecuenciaCita")
                .StartsAt(700L);

            modelBuilder.Entity("MediCita.Domain.Agenda.BloqueoAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Desde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "Desde");

                    b.ToTable("BloqueosDeAgenda", (string)null);
                });

            modelBuilder.Entity("MediCita.Domain.Agenda.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("DuracionCupoMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "Dia");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("MediCita.Domain.Catalogos.Especialidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Especialidades", (string)null);
                });

            modelBuilder.Entity("MediCita.Domain.Catalogos.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("MediCita.Domain.Citas.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Consultorio")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NotaConsulta")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SucursalId");

                    b.HasIndex("PacienteId", "FechaHoraInicio");

                    b.HasIndex(new[] { "MedicoId", "FechaHoraInicio" }, "IX_Citas_Cupo_Unico")
                        .IsUnique()
                        .HasDatabaseName("IX_Citas_Cupo_Unico")
                        .HasFilter("[Estado] IN (1, 2)");

                    b.HasIndex(new[] { "MedicoId", "FechaHoraInicio" }, "IX_Citas_Medico_Fecha");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("MediCita.Domain.Comun.LatidoDelWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Enviadas")
                        .HasColumnType("int");

                    b.Property<int>("Fallidas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Momento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Procesadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Momento")
                        .IsDescending();

                    b.ToTable("LatidosDelWorker", (string)null);
                });

            modelBuilder.Entity("MediCita.Domain.Comun.RegistroActividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Momento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Momento")
                        .IsDescending();

                    b.ToTable("Bitacora", (string)null);
                });

            modelBuilder.Entity("MediCita.Domain.Notificaciones.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanalEnvio")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("Estado", "FechaProgramada");

                    b.ToTable("Notificaciones", (string)null);

                    b.HasDiscriminator<string>("CanalEnvio").HasValue("Notificacion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediCita.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<int>("Rol");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediCita.Domain.Notificaciones.NotificacionCorreo", b =>
                {
                    b.HasBaseType("MediCita.Domain.Notificaciones.Notificacion");

                    b.HasDiscriminator().HasValue("Correo");
                });

            modelBuilder.Entity("MediCita.Domain.Notificaciones.NotificacionSms", b =>
                {
                    b.HasBaseType("MediCita.Domain.Notificaciones.Notificacion");

                    b.HasDiscriminator().HasValue("Sms");
                });

            modelBuilder.Entity("MediCita.Domain.Usuarios.Administrador", b =>
                {
                    b.HasBaseType("MediCita.Domain.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("MediCita.Domain.Usuarios.Medico", b =>
                {
                    b.HasBaseType("MediCita.Domain.Usuarios.Usuario");

                    b.Property<string>("Consultorio")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DuracionCitaMinutos")
                        .HasColumnType("int");

                    b.Property<Guid>("EspecialidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Exequatur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("SucursalId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MediCita.Domain.Usuarios.Paciente", b =>
                {
                    b.HasBaseType("MediCita.Domain.Usuarios.Usuario");

                    b.Property<string>("Alergias")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MediCita.Domain.Agenda.BloqueoAgenda", b =>
                {
                    b.HasOne("MediCita.Domain.Usuarios.Medico", null)
                        .WithMany("Bloqueos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediCita.Domain.Agenda.Horario", b =>
                {
                    b.HasOne("MediCita.Domain.Usuarios.Medico", null)
                        .WithMany("Horarios")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediCita.Domain.Citas.Cita", b =>
                {
                    b.HasOne("MediCita.Domain.Usuarios.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCita.Domain.Usuarios.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCita.Domain.Catalogos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("MediCita.Domain.Notificaciones.Notificacion", b =>
                {
                    b.HasOne("MediCita.Domain.Citas.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("MediCita.Domain.Usuarios.Medico", b =>
                {
                    b.HasOne("MediCita.Domain.Catalogos.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCita.Domain.Catalogos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("MediCita.Domain.Usuarios.Medico", b =>
                {
                    b.Navigation("Bloqueos");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
